#!/bin/bash
sudo systemctl stop fire
sudo rm -rv /var/log/fbd/*
sudo rm -rf /var/fire/config/*
sudo rm /etc/machine-id
sudo touch /etc/machine-id

[ -d $HOME/I2C/i2cdata/voltage ]  && [ rm $HOME/I2C/i2cdata/voltage/* ]
[ -d $HOME/I2C/i2cdata/status ]   && [ rm $HOME/I2C/i2cdata/status/* ]
[ -d $HOME/I2C/i2cdata/i2c ]      && [ rm $HOME/I2C/i2cdata/i2c/* ]
[ -d $HOME/I2C/i2cdata/gpio ]     && [ rm $HOME/I2C/i2cdata/gpio/* ]
[ -d $HOME/I2C/i2cdata/temp ]     && [ rm $HOME/I2C/i2cdata/temp/* ]
[ -d $HOME/I2C/i2cdata/MPU ]      && [ rm $HOME/I2C/i2cdata/MPU/* ]
[ -d $HOME/I2C/i2cdata/doorTemp ] && [ rm $HOME/I2C/i2cdata/doorTemp/* ]
[ -d $HOME/I2C/i2cdata/door ]     && [ rm $HOME/I2C/i2cdata/door/* ]
[ -d $HOME/I2C/i2cdata/dB ]       && [ rm $HOME/I2C/i2cdata/dB/* ]

rm $HOME/Watch.log
rm $HOME/Watch.bak

