#!/bin/bash
sudo systemctl stop fire
sudo rm -rv /var/log/fbd/*
sudo rm -rf /var/fire/config/*
sudo rm /etc/machine-id
sudo touch /etc/machine-id

[ -d /home/pi/I2C/i2cdata/voltage ]  && [ rm /home/pi/I2C/i2cdata/voltage/* ]
[ -d /home/pi/I2C/i2cdata/status ]   && [ rm /home/pi/I2C/i2cdata/status/* ]
[ -d /home/pi/I2C/i2cdata/i2c ]      && [ rm /home/pi/I2C/i2cdata/i2c/* ]
[ -d /home/pi/I2C/i2cdata/gpio ]     && [ rm /home/pi/I2C/i2cdata/gpio/* ]
[ -d /home/pi/I2C/i2cdata/temp ]     && [ rm /home/pi/pi/I2C/i2cdata/temp/* ]
[ -d /home/pi/I2C/i2cdata/MPU ]      && [ rm /home/pi/I2C/i2cdata/MPU/* ]
[ -d /home/pi/I2C/i2cdata/doorTemp ] && [ rm /home/pi/I2C/i2cdata/doorTemp/* ]
[ -d /home/pi/I2C/i2cdata/door ]     && [ rm /home/pi/I2C/i2cdata/door/* ]
[ -d /home/pi/I2C/i2cdata/dB ]       && [ rm /home/pi/I2C/i2cdata/dB/* ]

[ -e /home/pi/Watch.log ] && rm /home/pi/Watch.log
[ -e /home/pi/Watch.bak ] && rm /home/pi/Watch.bak
