#!/usr/bin/perl
use Date::Format;

my $epoch = $ARGV[0];
$epoch = time() unless defined($epoch);
my $utcstr = time2str("%c", $epoch,'UTC');
my $localstr = time2str("%c", $epoch,'EDT');
print "$epoch $utcstr UTC  $localstr EDT\n";

1;
