#!/bin/bash
if [ $# -eq 0 ]; then
   echo "Enter end to finish [1/2/3]  "
   read end
else 
   end=$1
fi

echo  "### Refresh git"
$HOME/APC_TestTools/stopRPi.pl kill
$HOME/APC_TestTools/gitAll
$HOME/APC_TestTools/pushRPi.sh

echo "###   Cleanup for fire and machine id"
sudo $HOME/APC_TestTools/cleanMachine
echo "## Mount rw to enable updates "
sudo mount -o remount,rw /
sudo mount -o remount,rw /boot
sudo systemctl stop fire
if  [ $end -eq 3 ];then
   echo  "Configure rLog"
   echo "###   Updating cron"
   crontab $HOME/updates/PiInstall/cron2.tab

   #echo " #### Setup SSD"
   #$HOME/updates/PiInstall/setupSSD.sh
   echo " ##### Gtting UIDs"
   $HOME/APC_TestTools/queryI2C.pl

   sudo systemctl enable fire
   $HOME/APC_TestTools/setPiHostname 0x55
elif [ $end -eq 1 ]  || [ $end -eq 2 ]; then
   echo "Configured end $end"
   sed -i 's/I2C_sleep=[^ ]*/I2C_sleep=0.01/' $HOME/RPi/config.ini
   echo " ### Updating cron "
   if [ $end -eq 1 ]; then 
      crontab $HOME/updates/PiInstall/cron1.tab
   else
      crontab $HOME/updates/PiInstall/cron2.tab
   fi
   echo " ##### Getting UIDs "
   $HOME/APC_TestTools/getUID
   Ard=`$HOME/APC_TestTools/I2Cio.pl read 0x0A 0x00 | cut -d' ' -f4`
   echo "Arduino Version $Ard"
   sudo systemctl enable fire
   $HOME/APC_TestTools/setPiHostname 0x51
else
   echo "Must enter end 1  2 or 3"
fi