#!/bin/bash
[ -z "$HOME" ] && $HOME="home/pi"
[ -d "$HOME/updates/RPi" ]       && $HOME/APC_TestTools/gitRev "Pi" 
[ -d  "$HOME/APC_TestTools" ]    && $HOME/APC_TestTools/gitRev "Tools" 
[ -d "$HOME/Arduino/Arduino" ]   && $HOME/APC_TestTools/gitRev "Ard" 
[ -d "$HOME/updates/PiInstall" ] && $HOME/APC_TestTools/gitRev "Install" 
[ -d "$HOME/NUC" ]               && $HOME/APC_TestTools/gitRev "NUC" 
[ -d "$HOME/updates/PiBinary" ]  && $HOME/APC_TestTools/gitRev "Binary" 
