#!/bin/bash

##### Check for read only file system
READONLY=0
sudo mount |grep ldata
[ "$?" == "0" ] && READONLY=1
sudo blkid | grep RW-LDATA
[ "$?" == "0" ] && READONLY=1
sudo mount |grep ' / ' | grep ro,
[ "$?" == "0" ] && READONLY=1
sudo mount |grep '/boot' | grep ro,
[ "$?" == "0" ] && READONLY=1

echo "$READONLY"
[ "$READONLY" == "0" ] && exit 1;

exit 0;
