#!/usr/bin/perl
#################################################
#
#
#	i2c_1WireAddy.pl
#
#
#   Get the addresses of the devices on the 1 Wire bus
#
#################################################
use lib "$ENV{HOME}/APC_TestTools";
use warnings;
use strict;
use RPi::I2C;

# Setup Signals
my %sig = ( HUP => 0, ABRT => 0, USR1 => 0, USR2 => 0, CONT => 0, QUIT => 0, STOP => 0, INT => 0 );
$SIG{HUP}  = sub {$sig{HUP} = 1};
$SIG{ABRT} = sub {$sig{ABRT} = 1};
$SIG{USR1} = sub {$sig{USR1} = 1};
$SIG{USR2} = sub {$sig{USR2} = 1};
$SIG{CONT} = sub {$sig{CONT} = 1};
$SIG{QUIT} = sub {$sig{QUIT} = 1};
$SIG{STOP} = sub {$sig{STOP} = 1};
$SIG{INT}  = sub {$sig{INT} = 1};

sub attach {
	my $addy = shift;
	my ($device,$retval);

	if ($device = RPi::I2C->new($addy)) {
		$retval = $device if ( $device->check_device($addy) );		
	}
	return ($retval);
}
         
sub readBus {
   if (my $device = attach(0x0f)) {
      my $numDevs = -1;
      while ($numDevs == -1 ) {
         $numDevs = $device->read_byte(0x04);
         sleep(1) if ($numDevs == -1 );
      }
      my $tempCnt = $numDevs;
      my $line = sprintf( "Found %02d devices on 1 Wire Bus\n",$numDevs);
      print $line;
      my $devNum = 0;
      while ($numDevs > 0) {
         $device->write_byte($devNum,0xA0);  # select the device address
         sleep(2);
         my @Address;
         for (my $i = 0; $i < 8; $i++ ) { 
            my $reg = 0xA1 + $i;
            $Address[$i] = -1;
            while ($Address[$i] == -1 ) {
               $Address[$i]  = $device->read_byte($reg);
               sleep(1) if $Address[$i] == -1;
            }
         }
         $line = sprintf( "Device %02d : %02X %02X %02X %02X %02X %02X %02X %02X\n",
            $devNum,@Address);
         print $line;
         $devNum++;
         $numDevs--;
      }
      my ($tmp1, $tmp2) = (-1,-1);
      while ($tmp1 == -1 ) {
         $tmp1 = $device->read_word(0x06) if ($tempCnt > 0);
         $tmp1 =  ( ((($tmp1 & 0x00FF) << 8) & 0xFF00) | ((($tmp1 & 0xFF00)>>8) & 0x00FF) ) / 10 
                   unless ($tmp1 == -1);
         sleep(1) if ($tmp1 == -1);
      }
      while ($tmp2 == -1) {
         $tmp2 = $device->read_word(0x08) if ($tempCnt > 1);
         $tmp2 =  ( ((($tmp2 & 0x00FF) << 8) & 0xFF00) | ((($tmp2 & 0xFF00)>>8) & 0x00FF) ) / 10
            unless ($tmp2 == -1);
         sleep(1) if ($tmp2 == -1);
      }
       print "Temp1 $tmp1   Temp2  $tmp2\n"
   } else {
      print "Error attaching to device 0x0F\n";
   }  
}

if ( defined($ARGV[0]) && ($ARGV[0] == 1) ) { 
   readBus();
} else { 
   while( ($sig{INT}==0) && ($sig{QUIT} == 0) &&
          ($sig{STOP} == 0) ) {
      readBus();
      sleep(15);
   }
}



1;
