#!/usr/bin/perl
use strict;
use warnings;

use RPi::I2C;

sub attach {
	my ($addy) = @_;
	my ($device,$retval);

	$device = RPi::I2C->new($addy);
	$device = RPi::I2C->new($addy) unless ($device); 	# one retry on attach
	if ($device) {
		$retval = $device if ( $device->check_device($addy) );		
	} else {
		my $err = $device->file_error();
		print "ERROR,Unable to attach to $addy,$err";
	}
	return ($retval);
}

sub getdBs {
	my ($peak1,$peak2,$avg1,$avg2,$max1,$max2) = (4095,4095,4095,4095,4095,4095);
    if (my $device = attach(0x0F) ) {
      	# Get the sound data
      	my $dbRetries = 4;
      	($peak1,$dbRetries) = trydBs($device,0x18,$dbRetries);
      	($peak2,$dbRetries) = trydBs($device,0x19,$dbRetries);
      	($avg1,$dbRetries)  = trydBs($device,0x1A,$dbRetries);
      	($avg2,$dbRetries)  = trydBs($device,0x1B,$dbRetries);
      	($max1,$dbRetries)  = trydBs($device,0x1C,$dbRetries);
      	($max2,$dbRetries)  = trydBs($device,0x1D,$dbRetries);
 
      	# Output if data collected  	
	my ($epoch,$msec) = Time::HiRes::gettimeofday();
	$peak1 = '' if ($peak1 == 4095);
	$peak2 = '' if ($peak2 == 4095);
	$avg1 = '' if ($avg1 == 4095);
	$avg2 = '' if ($avg2 == 4095);
	$max1 = '' if ($max1 == 4095);
	$max2 = '' if ($max2 == 4095);
	return($peak1,$peak2,$avg1,$avg2,$max1,$max2);
    }  
}	#	getdBs

while(1) {
	my @sounds = getdBs();
	my $line = join(',',@sounds);
	print "$line\n";
}

1;
