#!/usr/bin/perl
use strict;
use warnings;
use RPi::I2C;

my $UID_addy = hex($ARGV[0]);
print "ARGV $UID_addy \n";
my $UID;
my ($byte3, $byte4) = (-1,-1);

if (my $device = RPi::I2C->new($UID_addy)) {
   while ( ($byte3 = $device->read_byte(0xFE)) == -1 ) {sleep 0.33;}
   while ( ($byte4 = $device->read_byte(0xFF)) == -1 ) {sleep 0.33;}
   $UID=sprintf("%02X%02X",$byte3,$byte4);
} else {
   die $!;
}

my $Inirole = `grep myRole= $ENV{HOME}/RPi/config.ini`;
$Inirole =~ s/\R//g;
my ($name,$role) = split('=',$Inirole);
$role =~ s/\-//g;

my $mac = `cat /sys/class/net/eth0/address`;
$mac =~ s/\R//g;
my @parts = split(':',$mac);
my $MID=uc($parts[4]) . uc($parts[5]);
my $hostName = $role . '-' . $UID . '-' . $MID;

`sudo hostnamectl set-hostname $hostName`;
print "Hostname set to $hostName\n";
`$ENV{HOME}/APC_TestTools/fixHostName.pl`;
my $retval=`/sbin/ifconfig |grep -A 1 -e tun0 -e wlan1`;
print $retval;
$retval = `/usr/bin/hostnamectl`;
print $retval;

#print "Reboot now? [Y/n] ";
#my $ans = <STDIN>;
#$ans =~ s/\R//g;
#if ( (length($ans) == 0) || (uc($ans) eq 'Y') || (uc($ans) eq 'YES') ) {
#   print "Rebooting....";
#   sleep 1;
#   `sudo shutdown  -r now`;
#}

1;
