#!/usr/bin/perl
use strict;
use warnings;
my (%diskInfo,@diskIDs,@SDs,@smallSDs,@largeSDs);

sub getInputData {
   my ($msg,$default) = @_;

   print "$msg";
   my $resp = '';
   $resp = <STDIN>;
   $resp =~ s/\R//g;
   $resp =~ s/\s+//g;
   $resp = uc($resp);
   
   $resp = $default if (defined($default) && ($resp eq ''));
   return ($resp);
}

sub getYesNo {
   my ($msg,$default) = @_;

   print "$msg";
   my $resp = '';
   while ( ($resp ne 'Y') && ($resp ne 'N') ) {
      $resp = <STDIN>;
      $resp =~ s/\R//g;
      $resp = uc($resp);
      $resp = $default if (defined($default) && ($resp eq ''));
   }
   
   return ($resp);
}

### Get USB disk information
my $FORCE=0;
$FORCE=1 if ($ARGV[0] eq '-f');
my $sdDevs = `sudo blkid |grep /dev/sd`;
my @flds = split("\n",$sdDevs);
foreach my $curFld (@flds) {
   my ($dev,$data) = split(':',$curFld);
   push (@SDs,$dev);
   my $disk = substr($dev,0,8);
   my $diskDesc = `sudo fdisk -l $disk |head -2`;
   my @data = split(' ',$diskDesc);
   my $diskSize = $data[2];
   my $diskUnit = $data[3];
   $diskUnit =~ s/,//g;
   $diskInfo{$disk}->{size} = $diskSize;
   $diskInfo{$disk}->{unit} = $diskUnit;
   $diskInfo{$disk}->{desc} = $diskDesc;
   push(@smallSDs, $disk) if  ( ($diskUnit eq 'GiB') && ($diskSize < 200) );
   push(@largeSDs, $disk) if  ( ($diskUnit eq 'GiB') && ($diskSize > 200) );
}

### Display small SDs
my $numTargs = scalar(@smallSDs);
print "\n$numTargs small USB drives\n";
foreach my $curDrive (@smallSDs) {
   print"$curDrive \t$diskInfo{$curDrive}->{size} $diskInfo{$curDrive}->{unit}";
   my @lines = split("\n",$diskInfo{$curDrive}->{desc});
   print "\n\t" . join("\n\t",@lines) ."\n";
}
### Display Large SDs
$numTargs = scalar(@largeSDs);
print "\n$numTargs large USB drives\n";
foreach my $curDrive (@largeSDs) {
   print"$curDrive \t$diskInfo{$curDrive}->{size} $diskInfo{$curDrive}->{unit}";
   my @lines = split("\n",$diskInfo{$curDrive}->{desc});
   print "\n\t" . join("\n\t",@lines) ."\n";
}

my $targDev = '';
$targDev = $largeSDs[0] if (defined($largeSDs[0]));
my $continue = 'N';
if  ( scalar(@largeSDs) == 1 ) {
   if (defined($FORCE) ) {
      $continue = 'Y';
      print "Setting up data disk on $targDev\n";
   } else {
      $continue = getYesNo("\nSetup data disk on $targDev [Y,n] ?",'Y');   
   }
}

if ($continue eq 'Y') {
   my $targDrive = $targDev;
   $targDev .= '1';
   my $resp =    `sudo sfdisk --delete $targDrive`;
   print "Delete partition table $targDrive\n$resp\n";
   $resp = `sudo parted -a opt $targDrive mkpart primary ext4 0% 100%`;
   print "Create partition $targDrive\n$resp\n";
   ## File System
   $resp = `sudo mkfs.ext4 $targDev`;
   print "Create file system $targDev\n$resp\n";
   $resp = `sudo e2fsck -y -f $targDev`;
   print "e2fsck\n$resp\n";
   ## UUIDs
   $resp = `sudo tune2fs -U \$(uuid) $targDev`;
   print "$targDev UUID $resp\n";
   ## LABELs
   $resp = `sudo tune2fs -L DATA   $targDev`;
   print "$targDev LABEL $resp\n";
   my $blkid = `sudo blkid`;
   print "blkid\n$blkid\n";
   ## Files   
   `sudo mkdir /xdata` unless (-d '/xdata');
   $resp = `sudo mount $targDev /xdata`;
   if ($? ne 0) { die "Unable to mount $targDev on /xdata\t$!\n"; }
   print "Mounted $targDev at /xdata mounted \n";
   `sudo chmod 1777 /xdata`;
   `mkdir /xdata/NVR`           unless (-d '/xdata/NVR');
   `mkdir /xdata/NVR/Pending`   unless (-d '/xdata/NVR/Pending');
   `mkdir /xdata/NVR/Working`   unless (-d '/xdata/NVR/Working');
   `mkdir /xdata/NVR/Complete`  unless (-d '/xdata/NVR/Complete');
   `mkdir /xdata/rdata`         unless (-d '/xdata/rdata' );
   `mkdir /xdata/rdata/in`      unless (-d '/xdata/rdata/in' );
   `mkdir /xdata/rdata/out`     unless (-d '/xdata/rdata/out' );
   `mkdir /xdata/rdata/working` unless (-d '/xdata/rdata/working' );
   `mkdir /xdata/rLog`          unless (-d '/xdata/rLog' );
   `sudo umount  /xdata`;   
}

0;
