#!/bin/bash

usage () {
   NEW=$'\n'
   u="Usage:  startHDNVR${NEW}"
   u="$u          -I (--IP){231}${NEW}"
   echo "$u";
}
while [ "$1" != "" ]; do
    case $1 in
        -I | --IP )             shift
                                IPEND=$1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done
if [[ -z $IPEND ]] ;
then 
   usage
   exit 1
fi
IP="192.168.0.$IPEND"
LOGIP="HD$IPEND"
DATE=`date +%Y%m%d%H%M%S`
FNAME="HD${IPEND}_${DATE}"
cd /data/NVR/Working
CMD="/usr/local/bin/openRTSP -D 15 -c -B 200000 -b 200000 -4 -Q -F $FNAME -d 86400 -P 900 -t rtsp://$IP:554/ufirststream >>HD$IPEND.log 2>&1  &"
echo ""
`/usr/local/bin/openRTSP -D 15 -c -B 200000 -b 200000 -4 -Q -F $FNAME -d 86400 -P 900 -t rtsp://$IP:554/ufirststream >>HD$IPEND.log 2>&1  &`
tail $LOGIP.log
